// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzOsxXEOKUt57xY8Yii2MwuedCZ2_H6Q',
    appId: '1:666401944372:web:50713f1167807c434f2b61',
    messagingSenderId: '666401944372',
    projectId: 'blood-bank-c38c1',
    authDomain: 'blood-bank-c38c1.firebaseapp.com',
    storageBucket: 'blood-bank-c38c1.firebasestorage.app',
    measurementId: 'G-CME734S98H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSWl-2IdCzOHVfrSQMW4njPxiRwKJtU4M',
    appId: '1:666401944372:android:1ef933de7d635a584f2b61',
    messagingSenderId: '666401944372',
    projectId: 'blood-bank-c38c1',
    storageBucket: 'blood-bank-c38c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGeL11Q2Pugo3bxw4TxUbuxXqOsiJmX7w',
    appId: '1:666401944372:ios:6593d6eabec1b3524f2b61',
    messagingSenderId: '666401944372',
    projectId: 'blood-bank-c38c1',
    storageBucket: 'blood-bank-c38c1.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGeL11Q2Pugo3bxw4TxUbuxXqOsiJmX7w',
    appId: '1:666401944372:ios:6593d6eabec1b3524f2b61',
    messagingSenderId: '666401944372',
    projectId: 'blood-bank-c38c1',
    storageBucket: 'blood-bank-c38c1.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVzOsxXEOKUt57xY8Yii2MwuedCZ2_H6Q',
    appId: '1:666401944372:web:3bfa6341d73723714f2b61',
    messagingSenderId: '666401944372',
    projectId: 'blood-bank-c38c1',
    authDomain: 'blood-bank-c38c1.firebaseapp.com',
    storageBucket: 'blood-bank-c38c1.firebasestorage.app',
    measurementId: 'G-6E93ZMCKC8',
  );
}
